image:
  file: .gitpod.Dockerfile

# exposed ports
ports:
- port: 5432 # postgres
  onOpen: ignore

tasks:
  - init: |
      npm install -g npm
      npm i -g @bazel/bazelisk
      npm i -g @dataform/cli
      bazel build cli
    command:
      dataform help

# testing
#bazel test --build_tests_only -- ... -tests/integration/... -sql/...
