image:
  file: .gitpod.Dockerfile

tasks:
  - before: npm install -g npm
  - init: |
      npm i -g @bazel/bazelisk
      npm i -g @dataform/cli
      bazel build cli
    command:
      dataform help

# testing
#bazel test --build_tests_only -- ... -tests/integration/... -sql/...
